### ISSUE TITLE
Content on the site

### ISSUE THREAD

**Issue by NickCrowston** [dekay2323/pro3Issues#106]
Dem there are two periods missing in this on the site:
Powerful procurement and project management software**.** Maximize the accuracy and efficiency of your business processes with our intuitive software**.**

Issue here:
A program designed to be easy to use that offers standardized forms, L(no caps)ets you solicit, receive and evaluate bid(add an s), and award fully documented purchase orders.

**Comment by NickCrowston** [comment]
Also need to find and replace Pro3 with Procurable on the entire page

**Comment by dekay2323** [comment]
I find no instances of Pro3?
