### ISSUE TITLE
Testing live site thru procurableapp.com

### ISSUE THREAD

**Issue by NickCrowston** [dekay2323/pro3Issues#124]
To do for all of us over the next 1 - 2 weeks:

Test for bugs.
Identify some screen shots you'd like
Identify some instructional pop ups
Nick to do time trials

**Comment by NickCrowston** [comment]
This is as far as I could get tonight as I can't create bidders so I can't send out a quote

Comments:
When you go in to create an account change "Account" to "Company"
Can we make it so you can use your email or username to login?
Under Create Project - Lets Change "Code" to "Project Number"
Fields like Description that are text should have one of those count downs to tell you have many characters you have left.
Is there any way to have a drop down under Request for Quote for CREATE NEW that will take you to the screen that lets you Add a Request and then you'd just have to pick a project? 
Add a Procurement Plan Button to the Title Options

Bugs:
Hit Create Account = Message An Error Has Occurred (first password I chose was too short). Tried again and it worked.
Projects, Request for Quotes, Act As Vendor and Purchase Order only has titles no buttons. After flipping thru screens and trying things out the Create Project Button appeared
**Edit Bidders is Not Working Tried to Create Vendor - Received Error Message**
Cant type in new WBS Codes just get drop down options
Tried to Upload File and Got Error Message
Create VDDR does not work


Pop Ups
Home - This is your dashboard
Projects Button - Create Your New Project
Request for Quotes - View Your Request for Quotes (and Create New)
Purchase Orders - View Your Purchase Orders
Client - Create Your First Client
User - Create more Users On Your Account
Contact - Have a question? Found an Error? Want a Feature?
Act As Vendor - Submit Their Prices Yourself
When you Hover of a Red Project Name - Access The Procurement Plan

Screen Shots
Home Screen
Project List
Procurement Plan

**Comment by dekay2323** [comment]
I created 3 tickets for these, and started work on them.
Mainly I got rid of the create bidders bug, so that you can continue
testing.

Will deploy tonight and be live in 30 minutes

**Comment by NickCrowston** [comment]
Thanks Dem, I'll get the rest of my testing done over the weekend,

**Comment by cmcisaac** [comment]
I also got and error when trying to create a bidder, I used a made up email would that cause the error?

**Comment by NickCrowston** [comment]
I just checked my account again, I can get to this screen. As soon as I hit
create I get an error message. This is not a fake email.

Dem if we can get this sorted I will test to the end tonight

[image: Inline image 1]

**Comment by dekay2323** [comment]
I cannot see the screen

**Comment by NickCrowston** [comment]
I think this is closed, vendors seems to be working now

**Comment by dekay2323** [comment]
Seperate 3 issues
