### ISSUE TITLE
Nick Comments

### ISSUE THREAD

**Issue by dekay2323** [dekay2323/pro3Issues#127]
Comments:
When you go in to create an account change "Account" to "Company"
Can we make it so you can use your email or username to login?
Under Create Project - Lets Change "Code" to "Project Number"
Fields like Description that are text should have one of those count downs to tell you have many characters you have left.
Is there any way to have a drop down under Request for Quote for CREATE NEW that will take you to the screen that lets you Add a Request and then you'd just have to pick a project?
Add a Procurement Plan Button to the Title Options

**Comment by NickCrowston** [comment]
Another item, when creating line items we need to fix numerical order when I added in item 10 it went in between 1 & 2
![image](https://user-images.githubusercontent.com/28907205/28505534-19b4b06e-6fe2-11e7-9617-91d27ee19517.png)


FIXED - WORKS WITH ALPHANUMERIC

**Comment by NickCrowston** [comment]
We need full details for anyone we are adding into the system, specifically vendors and clients as this information needs to auto-populate onto the PO.
![image](https://user-images.githubusercontent.com/28907205/28505578-758d0a76-6fe2-11e7-8247-4cf9253b42f8.png)

**Comment by NickCrowston** [comment]
We need a back button to get form
EDIT MATERIAL REQUEST
![image](https://user-images.githubusercontent.com/28907205/28505601-ac320bee-6fe2-11e7-9bd6-631f1089d074.png)
to
PROCUREMENT PLAN
![image](https://user-images.githubusercontent.com/28907205/28505604-b7775f5e-6fe2-11e7-91ce-544f3f51081d.png)

DONE

**Comment by NickCrowston** [comment]
We should have a grand total at the bottom of the totals column, right next to the award PO button
![image](https://user-images.githubusercontent.com/28907205/28505939-eb9b19f4-6fe4-11e7-9a1b-086dceb28fa2.png)

**Comment by NickCrowston** [comment]
We need to separate users from vendors, they are different things. I'd rather have vendors have their own set up screen similar to the Client one
![image](https://user-images.githubusercontent.com/28907205/28506025-839a0364-6fe5-11e7-9958-c31b5c24f013.png)
- Will be done later
