### ISSUE TITLE
Nick Popups

### ISSUE THREAD

**Issue by dekay2323** [dekay2323/pro3Issues#129]
Pop Ups
Home - This is your dashboard
Projects Button - Create Your New Project
Request for Quotes - View Your Request for Quotes (and Create New)
Purchase Orders - View Your Purchase Orders
Client - Create Your First Client
User - Create more Users On Your Account
Contact - Have a question? Found an Error? Want a Feature?
Act As Vendor - Submit Their Prices Yourself
When you Hover of a Red Project Name - Access The Procurement Plan

**Comment by NickCrowston** [comment]
This is a big one. When acting as vendor or when the vendor is filling in an RFQ
CHECK OFF - Not bidding on this item (Pop up)
Alternatively we need to change the column header so it is more obvious.
![image](https://user-images.githubusercontent.com/28907205/28505802-0d27c050-6fe4-11e7-95d6-0e4fdff3b496.png)

**Comment by NickCrowston** [comment]
Also for above I'd like to have a brief reason if they are not quoting.,

**Comment by dekay2323** [comment]
I think these popups are a bit redundant. Projects is pretty clearly projects?
But these have been added

**Comment by dekay2323** [comment]
Changed column name and added popover
![bidding](https://user-images.githubusercontent.com/3060053/28649546-e7c28e16-7232-11e7-87b1-58e09d7847ae.png)
