### ISSUE TITLE
Project Number

### ISSUE THREAD

**Issue by cmcisaac** [dekay2323/pro3Issues#132]
How is this generated? I need to be able to assign custom project numbers. I put in a [Code] when opening a project (2017-001) and in the list it defaulted to 3

**Comment by dekay2323** [comment]
It is a string, not generated in anyway. You can put whatever you want in

**Comment by dekay2323** [comment]
![wrong](https://user-images.githubusercontent.com/3060053/28652041-94b098e8-7242-11e7-98bd-d7baa9edd95d.png)
