### ISSUE TITLE
Add another filed to Requests

### ISSUE THREAD

**Issue by cmcisaac** [dekay2323/pro3Issues#135]
This would be an additional field when adding the request and an additional column on the front Material Request Table

Field is Procurement Type and the options can be:

Material
Service
Other

**Comment by NickCrowston** [comment]
I like this one but what would fall under "other" isn't everything either a
material or service?

**Comment by cmcisaac** [comment]
I just put other in as a default in case there is something that we arent thinking of.

Maybe someone wants to procure software and sort it separately from material and services, 

I am fine with dropping other, it it probably a low probability situation.

**Comment by NickCrowston** [comment]
Sounds good to me

**Comment by dekay2323** [comment]
Sorry do you mean per Line Item on a request, or just on the request, so an extra column here?
![screenshot](https://user-images.githubusercontent.com/3060053/28508878-30d0df98-6ffb-11e7-8428-99bcd11d3f63.png)

**Comment by cmcisaac** [comment]
Just to the main request as show in your screenshot.

**Comment by NickCrowston** [comment]
I think it can just be called type

**Comment by dekay2323** [comment]
Done and added
