### ISSUE TITLE
Technical Instructions not being saved after Page refresh

### ISSUE THREAD

**Issue by cmcisaac** [dekay2323/pro3Issues#137]
Text in the Technical Instructions do not appear to be saved when the page is refreshed.
BEFORE
![image](https://user-images.githubusercontent.com/29044035/28496674-c8990cf6-6f2e-11e7-8cfa-6b7593d0d129.png)

AFTER UPLOADING A FILE AND GOING BACK
![image](https://user-images.githubusercontent.com/29044035/28496675-d7cb6304-6f2e-11e7-8709-86d5455500e2.png)

**Comment by dekay2323** [comment]
Fixed, saves on each button click.
Cleaned up buttons also, and table spacing
