### ISSUE TITLE
Vendor Login Accounts

### ISSUE THREAD

**Issue by NickCrowston** [dekay2323/pro3Issues#140]
I set up three vendors MRC, Apex, and TS&M. 
I am assuming after I set up passwords, via the password reset email that 
USERNAME: MRC
PASSWORD: MRCvendor 

but i can't log in as the vendor?

**Comment by dekay2323** [comment]
When u add a vendor, they get an email, and can enter their own password.
I am fixing the copy in this email though

**Comment by dekay2323** [comment]
I am working on new code around here, so the code is clearer and the emails

**Comment by dekay2323** [comment]
This should be clearer now, no password is auto set
