### ISSUE TITLE
Website Copy and Layout Changes

### ISSUE THREAD

**Issue by NickCrowston** [dekay2323/pro3Issues#150]
1. Move Open for Alpha Testing up into top right corner below login button
2. Change "Login" to "Login to App"
3. Change title "Video" to "Learn More", this also needs to be changed on the top button
4. Change title "Timing" to "Productivity Comparison" also change top button
5. Change graph title from "Excel" vs. to "Office Templates" vs. 
6. Change "Application" in top bar to "Intro"

I'll let Chris chime in on the slide idea for the 6 details sections.

**Comment by dekay2323** [comment]
Done
