### ISSUE TITLE
Icons

### ISSUE THREAD

**Issue by dekay2323** [dekay2323/pro3Issues#41]
For the static page I need to decide on icons for each chapter in the Overview
Choose icons from:

http://fontawesome.io/icons/

ALSO I would really like each major part of the app to have an icon, and maybe a specific color, so it is easy to know what section you are in.

Project
Material Request
Bid
Quote
PO

**Comment by NickCrowston** [comment]
I this our only option for icons? I'm having a hard time finding anything
applicable to our project

**Comment by dekay2323** [comment]
We can have someone make icons, in fact i suggest that.

Fivver probably

**Comment by dekay2323** [comment]
https://www.iconfinder.com/
https://piktochart.com/
https://www.pexels.com/
