### ISSUE TITLE
Icons

### ISSUE THREAD

**Issue by dekay2323** [dekay2323/pro3Issues#43]
We need icons and colors for each section

**Comment by dekay2323** [comment]
Project Dashboard - Fuel Gauge, speedometer
Plan - Map, flowchart, org chart
Auditability - Calculator, Abacus
Standardize Flow & Templates - Document (Font Awesome)
Intuitive - Lightbulb
Transparency - Window

**Comment by dekay2323** [comment]
https://www.iconfinder.com/
https://piktochart.com/
https://www.pexels.com/

**Comment by cmcisaac** [comment]
order placed.

**Comment by cmcisaac** [comment]
New Icons are saved here:

https://www.dropbox.com/sh/elem558y7j1lh9b/AADsK3QzF8HA4aEjFZHFMF4Aa?dl=0

also attached.
![transparency 1](https://user-images.githubusercontent.com/29044035/28481334-c3ba019e-6e21-11e7-9b7e-e73fd4ae6067.png)
![twitter](https://user-images.githubusercontent.com/29044035/28481339-c3c5b03e-6e21-11e7-8beb-92c28f8fa00b.png)
![auditability](https://user-images.githubusercontent.com/29044035/28481335-c3bc0462-6e21-11e7-8184-3be668ed1133.png)
![dashbaord 1](https://user-images.githubusercontent.com/29044035/28481336-c3be3598-6e21-11e7-96c3-4e146abc9733.png)
![email](https://user-images.githubusercontent.com/29044035/28481337-c3c127c6-6e21-11e7-8e01-fcf55172e643.png)
![intuitive 1](https://user-images.githubusercontent.com/29044035/28481338-c3c375bc-6e21-11e7-8214-6d6470a8669a.png)
![linkedin](https://user-images.githubusercontent.com/29044035/28481340-c3cc683e-6e21-11e7-81ec-0b03b56a0467.png)
![overview 1](https://user-images.githubusercontent.com/29044035/28481342-c3d76f68-6e21-11e7-9a25-c3abc50bfd6c.png)
![plan 1](https://user-images.githubusercontent.com/29044035/28481341-c3d65fa6-6e21-11e7-9192-949e0a800cfa.png)
![sandardized_flow_and_templates](https://user-images.githubusercontent.com/29044035/28481343-c3dc8110-6e21-11e7-96a2-309460007afa.png)

**Comment by dekay2323** [comment]
Missing the facebook icon
Maybe could we the P logo done in the same way
