### ISSUE TITLE
Overview

### ISSUE THREAD

**Issue by dekay2323** [dekay2323/pro3Issues#44]
Fast overview text

**Comment by NickCrowston** [comment]
Okay guys, heres my first crack at the page overview. Check it out and give feedback:

Do you feel stuck in the dark ages trying to execute your clients procurement needs using endless Office templates?
Is your team’s productivity suffering from repetitive data entry, confusion resulting from multiple versions of your templates and tools, and difficulty locating data in endless folder structures?
Let Procurable provide the solution!
Procurable allows you to integrate the communication of the supply chain from vendor to client.
Procurable offers a low monthly cost per seat, with no set up fees, training fees, or maintenance costs. In addition, there is no contractual obligation. Pay for what you use for as long as you use it.
A program designed to be easy to use that offers standardized forms, Lets you solicit, receive and evaluate bid, and award fully documented purchase orders.

**Comment by dekay2323** [comment]
I like it, where does it go, does it replace the five headings or just the one I created? Truthfully I like this more than all the others

**Comment by NickCrowston** [comment]
This would just replace the high level overview, it needs a bit of a polish still I think.
