### ISSUE TITLE
Add Projects to the menu at the top

### ISSUE THREAD

**Issue by cmcisaac** [dekay2323/pro3Issues#47]
Currently Menu has
Procurement Stats
Material Request
Request for Quote
Purchase Order
Act as Vendor

I would like this to be rearrange this. 

So the  "all the time " menu options should be 

Home --> Projects 

Home should bring you to the Procurement Stats Page

Projects, by default brings you to the Project List, sorted by Client and should have a submenu open underneath. with the following

Projects --> MR --> RFQ

Act as Vendor needs to move to the settings dropdown.

**Comment by cmcisaac** [comment]
Also, Move Home --> Projects into the Blue Section.

**Comment by dekay2323** [comment]
Mostly done with some parts not 100%

**Comment by dekay2323** [comment]
Procurable - Home - Projects

**Comment by dekay2323** [comment]
Chris is this better, I have not added the submenu yet
