### ISSUE TITLE
Sign up email response

### ISSUE THREAD

**Issue by NickCrowston** [dekay2323/pro3Issues#57]
Hey guys, please take a look at this for the email response when people sign up on the website and comment

Thank you for your interest in Procurable! 
We are excited to bring a simple and efficient solution to the worlds infrastructure project procurement needs. Stay tuned for updates on the release of the Procurable Procurement Module.
We would be very interested in speaking with you briefly regarding the needs of your business, a representative from Procurable will be in touch in the near future.

**Comment by dekay2323** [comment]
Right now that will be the message after submittingr

**Comment by dekay2323** [comment]
DONE
