### ISSUE TITLE
New video review

### ISSUE THREAD

**Issue by NickCrowston** [dekay2323/pro3Issues#82]
Noticed the new video mentions "Create and use standardized forms". Should we have the word create in there?

**Comment by NickCrowston** [comment]
Also says "Track and store vendor documents" which she doesn't do yet

**Comment by dekay2323** [comment]
We do track and store vendor docs. They are files on a material request

**Comment by NickCrowston** [comment]
Yes we do have that but its not set up to an appropriate level of document control yet. This is likely going to be our next phase, will include document status, transmittal, and squad checking.

**Comment by cmcisaac** [comment]
Feedback has been given to video guy, just waiting to hear back.

**Comment by cmcisaac** [comment]
New Video is live - New link here:

https://youtu.be/tTfmEIW47R0
